version: "3.9"  # optional since v1.27.0
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true" 
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8000:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      vpcbr:
        ipv4_address: 10.1.10.2
    labels:
      - traefik.http.routers.traefik=true
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_traefik.rule=Host(`traefik.${COMPOSE_PROJECT_NAME}.local`)

  strapi:
    container_name: ${COMPOSE_PROJECT_NAME}_strapi4
    image: node:fermium-slim
    working_dir: /srv 
    command: sh -c "chmod +x /srv/run/develop.sh && exec /srv/run/develop.sh"
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ../apps/strapi:/app/strapi
      - ../setup/strapi/dbconfig:/srv/config
      - ../setup/strapi/run:/srv/run
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.1.10.3
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_strapi.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_strapi.rule=Host(`cms.${COMPOSE_PROJECT_NAME}.local`)        

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ../apps/mariadb:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.1.10.4      
  node:
    image: node:fermium-slim
    container_name: ${COMPOSE_PROJECT_NAME}_node
    mem_limit: 2G
    environment:  
      VITE_SERVER_PORT: "3003"
    working_dir: /home/node/react    
    command: sh -c 'tail -f /dev/null'
    ports:
      - 3003:3003
    volumes:
      - ../apps/react:/home/node/react
      - ../setup/react:/setup
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_node.rule=Host(`dev.${COMPOSE_PROJECT_NAME}.local`)

  react:
    image: nginx:1.20.1-alpine
    hostname: react
    container_name: ${COMPOSE_PROJECT_NAME}_react
    volumes:
      - ../apps/react/dist:/usr/share/nginx/html
      - ../setup/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      vpcbr:
        ipv4_address: 10.1.10.5
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_react.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_react.rule=Host(`www.${COMPOSE_PROJECT_NAME}.local`,`${COMPOSE_PROJECT_NAME}.local`)

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/16
         gateway: 10.1.10.1